# Generated by Django 3.2.20 on 2024-03-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldiersdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Soldierip', models.CharField(max_length=15)),
                ('Humidity', models.CharField(max_length=15)),
            ],
        ),
    ]
