# Generated by Django 3.2.20 on 2024-03-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_locationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Soldierip', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=50)),
                ('Rank', models.CharField(max_length=20)),
                ('Alive', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='Soldierip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.soldier'),
        ),
        migrations.AlterField(
            model_name='soldiersdata',
            name='Soldierip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.soldier'),
        ),
    ]
