# Generated by Django 3.2.20 on 2024-03-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240316_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldiersdata',
            name='Temperature',
            field=models.IntegerField(default=0, verbose_name=4),
            preserve_default=False,
        ),
    ]
