# Generated by Django 3.2.20 on 2024-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_soldiersdata_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldiersdata',
            name='Temperature',
            field=models.IntegerField(),
        ),
    ]
