# Generated by Django 3.2.20 on 2024-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_soldiersdata_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldiersdata',
            name='East',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldiersdata',
            name='Needhelp',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldiersdata',
            name='North',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldiersdata',
            name='South',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldiersdata',
            name='West',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
