# Generated by Django 3.2.20 on 2024-04-29 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20240325_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldiersdata',
            name='HeartBeat',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=20)),
                ('Direction', models.CharField(max_length=10)),
                ('Soldierip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.soldier')),
            ],
        ),
    ]
